//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StuldastolClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionStatusLogs
    {
        public int Id { get; set; }
        public int ProductionOrderId { get; set; }
        public int StatusId { get; set; }
        public int ChangedBy { get; set; }
        public System.DateTime ChangedAt { get; set; }
    
        public virtual ProductionOrders ProductionOrders { get; set; }
        public virtual ProductionStatuses ProductionStatuses { get; set; }
        public virtual Users Users { get; set; }
    }
}
