//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StuldastolClient
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StuldastolEntities : DbContext
    {
        public StuldastolEntities()
            : base("name=StuldastolEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CartItems> CartItems { get; set; }
        public virtual DbSet<Carts> Carts { get; set; }
        public virtual DbSet<OrderItems> OrderItems { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<OrderStatuses> OrderStatuses { get; set; }
        public virtual DbSet<PasswordResetCodes> PasswordResetCodes { get; set; }
        public virtual DbSet<ProductionOrders> ProductionOrders { get; set; }
        public virtual DbSet<ProductionStatuses> ProductionStatuses { get; set; }
        public virtual DbSet<ProductionStatusLogs> ProductionStatusLogs { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<PromoCodes> PromoCodes { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<ConsultationRequests> ConsultationRequests { get; set; }
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<ProductionTasks> ProductionTasks { get; set; }
    }
}
