//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StuldastolClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionOrders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductionOrders()
        {
            this.ProductionStatusLogs = new HashSet<ProductionStatusLogs>();
            this.ProductionTasks = new HashSet<ProductionTasks>();
        }
    
        public int Id { get; set; }
        public int OrderId { get; set; }
        public int ProductId { get; set; }
        public int Quantity { get; set; }
        public string WoodType { get; set; }
        public string OilColor { get; set; }
        public string FabricType { get; set; }
        public System.DateTime Deadline { get; set; }
        public string DeliveryAddress { get; set; }
        public bool IsSelfPickup { get; set; }
        public int CurrentStatusId { get; set; }
        public int AssignedTo { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual Products Products { get; set; }
        public virtual ProductionStatuses ProductionStatuses { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductionStatusLogs> ProductionStatusLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductionTasks> ProductionTasks { get; set; }
    }
}
