//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StuldastolProduction
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionTasks
    {
        public int Id { get; set; }
        public int ProductionOrderId { get; set; }
        public string TaskName { get; set; }
        public int StatusId { get; set; }
        public string ImagePath { get; set; }
        public int TotalCount { get; set; }
        public Nullable<int> CompletedCount { get; set; }
    
        public virtual ProductionOrders ProductionOrders { get; set; }
    }
}
