//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StuldastolProduction
{
    using System;
    using System.Collections.Generic;
    
    public partial class PasswordResetCodes
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string Code { get; set; }
        public System.DateTime ExpiresAt { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
